[tool.briefcase]
project_name = "Farmasave"
bundle = "com.spyalekos"
version = "2.6.0"
url = "https://github.com/spyalekos/farmasave"
license.text = "Other/Proprietary"
author = "SpyAlekos"
author_email = "spyalekos@gmail.com"

[tool.briefcase.app.farmasave]
formal_name = "Farmasave"
description = "Διαχειριστής Φαρμάκων"
version = "2.6.0"
sources = ["src/farmasave"]
requires = [
    "fpdf2>=2.8.5",
]

[tool.briefcase.app.farmasave.macOS]
requires = [
    "toga-cocoa~=0.5.0",
]

[tool.briefcase.app.farmasave.linux]
requires = [
    "toga-gtk~=0.5.0",
    "pygobject < 3.52.1",
]

[tool.briefcase.app.farmasave.windows]
requires = [
    "toga-winforms~=0.5.0",
]

[tool.briefcase.app.farmasave.android]
requires = [
    "toga-android~=0.5.0",
    "rubicon-java>=0.2.6",
]
build_gradle_dependencies = [
    "androidx.appcompat:appcompat:1.6.1",
    "com.google.android.material:material:1.9.0",
]
permissions = [
    "android.permission.READ_EXTERNAL_STORAGE",
    "android.permission.WRITE_EXTERNAL_STORAGE",
    "android.permission.MANAGE_EXTERNAL_STORAGE",
    "android.permission.CAMERA",
]

[tool.briefcase.app.farmasave.iOS]
requires = [
    "toga-ios~=0.5.0",
]
